### ISSUE TITLE
Glassed detection and location

### ISSUE THREAD

**Issue by alfredtorres** [cleardusk/MeGlass#1]
Excuse me ,im a PhD student and now solving the glassed detection problem.
Thank you very much for you opened MeGlass dataset.
And will you open you code in your paper later?

**Comment by cleardusk** [comment]
My future plan is to release the code for adding eyeglass in a binary format, but it may need some time.

**Comment by alfredtorres** [comment]
that's cool.
I will keep watch this repo.

**Comment by ysc703** [comment]
@cleardusk When will you release the binary files? Thanks a lot!
