### ISSUE TITLE
您好，近期还有开源代码的计划吗

### ISSUE THREAD

**Issue by w8501** [cleardusk/MeGlass#14]

**Comment by cleardusk** [comment]
暂时无开源规划。可以参考 [3DDFA_V2](https://github.com/cleardusk/3DDFA_V2/) 重构人脸，然后对 3D eyeglass 进行配准，渲染来实现。

**Comment by w8501** [comment]
> 暂时无开源规划。可以参考 [3DDFA_V2](https://github.com/cleardusk/3DDFA_V2/) 重构人脸，然后对 3D eyeglass 进行配准，渲染来实现。

好的，谢谢！
