### ISSUE TITLE
The specific method of eyeglass faces synthesis in your paper?

### ISSUE THREAD

**Issue by hanson-young** [cleardusk/MeGlass#3]
I am trying your method to improve the performance of my face recognition model.But I can't understand clearly，How are these eyeglass faces generated concretely？How do you blend 'Synthetic Result' from 'Input Face Image' and '3DMM face model' ? Can you give me some advice? Thx!

**Comment by cleardusk** [comment]
The original eyeglass is 3D mesh.
3DMM face model is used to estimate 3D face dense model represented by 3DMM params. Then 3D eyeglass mesh is fitted to 3D face model by anchor points. My early plan is to release the code, but I am so busy these months. I will release the code or write a blog if time permitted.

**Comment by hanson-young** [comment]
目前我正在用opengl去复现结果,但还是不熟悉,能告诉我你实现的时候用的是什么工具?另外,方便加个微信吗?我的微信号是13379507125
