### ISSUE TITLE
segmentation masks?

### ISSUE THREAD

**Issue by ldenoue** [cleardusk/MeGlass#4]
Do you have the ground truth for segmentation masks of where the glasses are on each image?
Specifically, I would like to know the ground-truth masks for pixels that correspond to the glass of the eyeglasses (I'm building an eyeglass segmentation network).

**Comment by cleardusk** [comment]
Sorry for that MeGlass dataset only contains images with or without eyeglasses,  there are no ground truth masks for eyeglasses. : (
