### ISSUE TITLE
For the same identity, how can i judge the images with or without eyeglasses? 

### ISSUE THREAD

**Issue by zllrunning** [cleardusk/MeGlass#5]
Excuse me, this file, named MeGlass_120x120.zip, only contains 47917 images. And according to the naming rule, I can just distinguish the face image's identity.  But how can I judge the images with or without eyeglasses for the same identity?

**Comment by cleardusk** [comment]
`meta.txt` contains the eyeglass labels of images, each image name corresponds to one label. `1` means black-eyeglass, `0` means no-eyeglass. Tks for your attention.

**Comment by zllrunning** [comment]
Thanks for you reply!
